name: Publish VS Code Extension

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: npm ci

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Package extension
        run: vsce package

      - name: Get VSIX filename
        id: get-vsix-filename
        run: echo "VSIX_FILENAME=$(ls *.vsix)" >> $GITHUB_OUTPUT

      - name: Publish to Visual Studio Marketplace
        run: vsce publish -p ${{ secrets.VSCE_PAT }}
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}

      - name: Upload VSIX as release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_PAT }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.get-vsix-filename.outputs.VSIX_FILENAME }}
          asset_name: ${{ steps.get-vsix-filename.outputs.VSIX_FILENAME }}
          asset_content_type: application/octet-stream
