name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  runs-on: ubuntu-latest
  environment: release

  release-please:
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GIT_PAT }}
